[template]
src         = "nginx.tmpl"
dest        = "/etc/nginx/conf.d/default.conf"
keys        = ["services"]
owner       = "nginx"
mode        = "0644"
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "service nginx reload"